{{- if .Values.backend.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "app.shortname" . }}-backend-pvc
  {{- with .Values.backend.persistence.annotations  }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size | quote }}
  {{- if .Values.backend.persistence.storageClass }}
  {{- if (eq "-" .Values.backend.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.backend.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  {{- end }}