apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.shortname" . }}-backend-secret
type: Opaque
data:
  DB_USERNAME: {{ .Values.mysql.mysqlUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.mysql.mysqlPassword | b64enc | quote }}